//  Get all books
export const ALL_BOOKS_REQUESTED = "ALL_BOOKS_REQUESTED";
export const ALL_BOOKS_SUCCEEDED = "ALL_BOOKS_SUCCEEDED";
export const ALL_BOOKS_FAILED = "ALL_BOOKS_FAILED";

//  Get one book
export const BOOK_BY_ID_REQUESTED = "BOOK_BY_ID_REQUESTED";
export const BOOK_BY_ID_SUCCEEDED = "BOOK_BY_ID_SUCCEEDED";
export const BOOK_BY_ID_FAILED = "BOOK_BY_ID_FAILED";

//  Add New book
export const ADD_BOOK_REQUESTED = "ADD_BOOK_REQUESTED";
export const ADD_BOOK_SUCCEEDED = "ADD_BOOK_SUCCEEDED";
export const ADD_BOOK_FAILED = "ADD_BOOK_FAILED";

//  Edit book
export const EDIT_BOOKS_REQUESTED = "EDIT_BOOKS_REQUESTED";
export const EDIT_BOOKS_SUCCEEDED = "EDIT_BOOKS_SUCCEEDED";
export const EDIT_BOOKS_FAILED = "EDIT_BOOKS_FAILED";

//  View book
export const VIEW_BOOK_REQUESTED = "VIEW_BOOK_REQUESTED";
export const VIEW_BOOK_SUCCEEDED = "VIEW_BOOK_SUCCEEDED";
export const VIEW_BOOK_FAILED = "VIEW_BOOK_FAILED";

//  Delete book
export const DELETE_BOOKS_REQUESTED = "DELETE_BOOKS_REQUESTED";
export const DELETE_BOOKS_SUCCEEDED = "DELETE_BOOKS_SUCCEEDED";
export const DELETE_BOOKS_FAILED = "DELETE_BOOKS_FAILED";